### ISSUE TITLE
when i changed the values for Pic18f26k22 in db .its not working

### ISSUE THREAD

**Issue by qasimali-byte** [malessandrini/an1310-python#1]
changing values in db for Pic18f26k22 not working

**Comment by malessandrini** [comment]
Hi, what have you changed? All the values must be changed accordingly to what's in the original database from Microchip (devices.db).
What output/error have you got?
Unfortunately I cannot test that specific device.

**Comment by qasimali-byte** [comment]
hi, Thanks for your kind Reply i changed the all values accordingly the microchip database.


	device_db = (
		# read from original devices.db (sqlite), table DEVICES, excluding DEVICEROWID field
		# 0: device_id, 1: family_id, 2: PARTNAME, 3: BYTESPERWORDFLASH, 4: WRITEFLASHBLOCKSIZE, 5: ERASEFLASHBLOCKSIZE, 6: STARTFLASH, 7: ENDFLASH,
		# 8: STARTEE, 9: ENDEE, 10: STARTUSER, 11: ENDUSER, 12: STARTCONFIG, 13: ENDCONFIG, 14: STARTDEVICEID, 15: ENDDEVICEID, 16: DEVICEIDMASK, 17: STARTGPR, 18: ENDGPR
		(674,4,'PIC18F26k22',2,64,64,0,65536,15728640,15729664,2097152,2097160,3145728,3145742,4194302,4194304,65504,0,3896),
	)


and get the following error.


        Traceback (most recent call last):
          File "./an1310.py", line 382, in <module>
            sys.exit(main(None if args.p is None else args.p[0], args.hexFile))
          File "./an1310.py", line 42, in main
            bl.connect()
          File "./an1310.py", line 131, in connect
            reply = self.get_reply(12)
          File "./an1310.py", line 336, in get_reply
            raise RuntimeError('no reply or wrong packet received')
        RuntimeError: no reply or wrong packet received

**Comment by malessandrini** [comment]
It seems that the port is opened correctly, but the PIC is not replying.
Did you use the correct port?
Do the bottloader work with the Micrcochip AN1310 original program?

**Comment by qasimali-byte** [comment]
yes, I used the correct port which is in my case  /dev/ttyUSB0. and when I upload the hex file  using an1310 on a window 10 it's working fine.

**Comment by qasimali-byte** [comment]
> It seems that the port is opened correctly, but the PIC is not replying.
> Did you use the correct port?
> Do the bottloader work with the Micrcochip AN1310 original program?

yes, I used the correct port which is in my case  /dev/ttyUSB0. and when I upload the hex file using an1310 on a window 10 it's working fine.

**Comment by malessandrini** [comment]
It's strange because it's failing at the very first phase of communication, it's not a matter of specific values for that PIC.
I have to admit that I tested it just for one device, and I cannot help you very much.
What about using a lower baud rate (line 112)? I often had problems with that.

**Comment by qasimali-byte** [comment]
> It's strange because it's failing at the very first phase of communication, it's not a matter of specific values for that PIC.
> I have to admit that I tested it just for one device, and I cannot help you very much.
> What about using a lower baud rate (line 112)? I often had problems with that.

I used 115200. what do you suggest?

**Comment by malessandrini** [comment]
The bootloader on the PIC has auto-detection, try 9600 for example, should be low enough.

**Comment by qasimali-byte** [comment]
![image](https://user-images.githubusercontent.com/59023310/110138121-747ff580-7df3-11eb-90bb-4a67dc4b708f.png)

**Comment by qasimali-byte** [comment]
> The bootloader on the PIC has auto-detection, try 9600 for example, should be low enough.

![image](https://user-images.githubusercontent.com/59023310/110138222-8e213d00-7df3-11eb-8990-353818d426a3.png)

**Comment by qasimali-byte** [comment]
> The bootloader on the PIC has auto-detection, try 9600 for example, should be low enough.

 when I tried on  an1310 using the following settings it's working fine.
![WhatsApp Image 2021-03-05 at 8 42 05 PM](https://user-images.githubusercontent.com/59023310/110138374-b9a42780-7df3-11eb-8897-323c48a6dd04.jpeg)

**Comment by qasimali-byte** [comment]
> The bootloader on the PIC has auto-detection, try 9600 for example, should be low enough.

did you find any solution?

**Comment by malessandrini** [comment]
Sorry I have no more ideas! Maybe the bootloader works differently for PIC16 and PIC18, being quite different architectures.
